### ISSUE TITLE
Erreur à l'installation

### ISSUE THREAD

**Issue by Sigri44** [LaBaleineFr/LaBaleineDeWallStreet#2]
Bonjour,

Voici mon erreur lors de l'installation.

Je viens de passer de Python 2.7 à Python 3.2, j'ai installé PIP, et désormais : 

```
sudo pip-3.2 install -r requirements.txt -i https://pypi.python.org/simple/

Downloading/unpacking requests (from -r requirements.txt (line 1))
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/scripts/LaBaleineDeWallStreet/build/requests/setup.py", line 55, in <module>
        exec(f.read(), about)
      File "<string>", line 14
        __cake__ = u'\u2728 \U0001f370 \u2728'
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/scripts/LaBaleineDeWallStreet/build/requests/setup.py", line 55, in <module>

    exec(f.read(), about)

  File "<string>", line 14

    __cake__ = u'\u2728 \U0001f370 \u2728'

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/scripts/LaBaleineDeWallStreet/build/requests
Storing complete log in /root/.pip/pip.log
```

**Comment by daodevinc** [comment]
Résolu : Je suis passé à la 3.6.2 et ça marche !
